name: Publish plugin
on: workflow_dispatch
jobs:
  publish:
    name: Publish to JetBrains marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: eskatos/gradle-command-action@v1
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          arguments: publishPlugin
